### ISSUE TITLE
bug: Pomodoro Timer

### ISSUE THREAD

**Issue by HONGMOEJI** [ChackTeam/Chack#22]
휴식시간이 시작될 때와 끝날 때, "휴식 시간이 시작되었습니다. 잠시 쉬어가세요!"  Snackbar 메시지가 중복되어 출력됨.

**Comment by Moonbjin** [comment]
버그 사항 인지하였고, 버그 수정해서 Pull request 넣겠습니다.

**Comment by HONGMOEJI** [comment]
Fixes #22
